"""correct relationship between word and word set

Revision ID: 12cdfab35e2b
Revises: c450af9dca21
Create Date: 2023-09-25 17:10:14.547035

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '12cdfab35e2b'
down_revision = 'c450af9dca21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_set_connector')
    op.add_column('word', sa.Column('set_id', sa.Integer(), nullable=False, server_default=sa.text('1')))
    op.create_foreign_key(None, 'word', 'word_set', ['set_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'word', type_='foreignkey')
    op.drop_column('word', 'set_id')
    op.create_table('word_set_connector',
    sa.Column('word_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('set_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['set_id'], ['word_set.id'], name='word_set_connector_set_id_fkey'),
    sa.ForeignKeyConstraint(['word_id'], ['word.id'], name='word_set_connector_word_id_fkey'),
    sa.PrimaryKeyConstraint('word_id', 'set_id', name='word_set_connector_pkey')
    )
    # ### end Alembic commands ###
