"""add exmaple to words

Revision ID: 1855a86b6233
Revises: bf1b6b9ac210
Create Date: 2024-04-14 13:49:34.522340

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '1855a86b6233'
down_revision = 'bf1b6b9ac210'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word', sa.Column('example', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('word', 'example')
    # ### end Alembic commands ###
