"""add is_bot attr for users

Revision ID: c450af9dca21
Revises: f9c9d55f70b1
Create Date: 2023-09-17 19:48:40.235753

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = 'c450af9dca21'
down_revision = 'f9c9d55f70b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('et_user', sa.Column('is_bot', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('et_user', 'is_bot')
    # ### end Alembic commands ###
